name: "Check PR for specific strings and comment on the PR if found"
description: "Checks the body of a pull request for given strings. Will leave a comment if any of them are found so the reviewer knows to focus on them."
author: "Josh Foschi"
branding:
  icon: "git-pull-request"
  color: "gray-dark"
inputs:
  searchTerms:
    required: true
    description: "strings to search for. Github actions do not accept lists, to search multiple strings please seperate with commas."
runs:
  using: "node16"
  main: "dist/index.js"
